### ISSUE TITLE
bundling

### ISSUE THREAD

**Issue by ghost** [licensezero/licensezero-faq#12]
I have several independently maintained projects that are related. I would like to offer a single license for these several related projects. Is this possible with the current l0 tools and if so what would the steps for doing that look like?

**Comment by kemitchell** [comment]
@substack Hmm. Are the projects dependencies of one another, or entirely separate code?

**Comment by ghost** [comment]
These would not necessarily be dependencies, but tools that work well together. I think this would be nice so that I can offer one license for a whole stack instead of having to license each component separately or to merge everything into one repository.

If it's easier, I would be fine with adding a note to some projects that if you have a license for X, you have a license for this project too. But it would be good if the licensezero tool understood this.

**Comment by kemitchell** [comment]
Command-line tools, perhaps? The kind of thing folks would list in package.json, or perhaps something they'd rather `npm i -g $THING`?

**Comment by kemitchell** [comment]
If the issue is whether `licensezero quote` will do the right thing, and not quote a license for A if they already bought B, the answer to your question is probably yes, with a few small changes. You would use a single License Zero "project", and associated project UUID, for all projects in the "package".

**Comment by kemitchell** [comment]
This is not a use case that I've really considered so far, so I'd want to step through it.

**Comment by kemitchell** [comment]
@substack, might you have a single project-page or documentation URL for all the pieces of a project, or all the parts of a bundle. For example, a GitHub Pages site for an org holding all the Git repos?

**Comment by kemitchell** [comment]
@substack, I've taken a pass through this in the context of L0's forthcoming transition toward dev-to-dev licensing. The to-dos here will be to create some URL for the project as a whole, a kind of umbrella project page, and use that as the homepage of the project, rather than a repository URL. You can then copy the signed L0 metadata from one package.json to another. Your contributions to all packages with that metadata will be covered by private licenses for the project as a whole.

**Comment by kemitchell** [comment]
@substack, the system now asks for a "homepage" for each project, rather than a "repository" URL. The agreements also avoid tying anything like license scope to commits in a repository.

That should make it possible for you to create a single project, with a description that encompasses multiple tools or libraries, and a homepage that covers all of them. You can then `l0 license $SAME_PROJECT_ID` in all relevant npm packages, injecting the same project ID into `package.json`. When folks run `l0 quote` or `l0 buy` with a license for the project, it will correctly ignore other packages with the same project ID.
