### ISSUE TITLE
Does it make sense to dual license using Parity as well as Prosperity?

### ISSUE THREAD

**Issue by makkus** [licensezero/licensezero-faq#13]
I'm wondering whether it can make sense to release a project using both Parity & Prosperity licenses, giving the user a choice which one to use it under, while still offering the option of a private license in case none of the restrictions of Parity or Prosperity is acceptable.

An example would be a build tool, which could be used to build and deploy websites. If using Parity, all parts of the resulting web-page would need to be open-sourced, even if it wasn't intended for commercial purposes, right (I might be wrong there though)? If using Prosperity, that usage would be acceptable, but on the other hand people would not have the freedom to build commercial open-source projects with it, which would be an acceptable default usage.

An addon-question, related to this: would it be allowed to build software that uses ('normal' open-source) non LicenseZero licenses like GPL or Apache with a built tool that uses Parity as its license?

**Comment by kemitchell** [comment]
@makkus, thanks for this question.

Offering both Parity and Prosperity terms for the same work---the same licensezero.com "project"---isn't something I'd considered before you mentioned it. I'm not aware of any technical reason it couldn't be done. And oddly enough, I think the current [private license terms](https://licensezero.com/licenses/private) would have the intended effect. But one public license is complex enough, and two more than twice as complex. Even when they share a lot of language in common, as do Parity and Prosperity.

I _did_ consider situations where one piece of software, say a library, is made of multiple licensezero.com projects that cover different contributions, and under different public licenses. See in particular [the Guide section on stacking metadata](https://guide.licensezero.com/#stacked-licensing).

As for how particular kinds of software play out under the license terms, both License Zero documentation and the licenses have short summaries of their intended effect. But whenever you have a question about how the licenses work, I strongly recommend that you look at the license texts, which were written to be easy to read. ([Parity](https://licensezero.com/licenses/parity), [Prosperity](https://licensezero.com/licenses/prosperity)) In particular, take a pass through the numbered rules in each license.

I would read Parity to require release of source code for software parts of a website created with a Parity-licensed build tool. I _wouldn't_ read Parity to require release of preferred source for HTML, CSS, images, and other aspects of the website. If you can comfortably read Parity's rules differently, do let me know!

**Comment by kemitchell** [comment]
> An addon-question, related to this: would it be allowed to build software that uses ('normal' open-source) non LicenseZero licenses like GPL or Apache with a built tool that uses Parity as its license?

Might you open that as a separate issue on the repo for Parity? <https://github.com/licensezero/parity-public-license/issues>

Thanks.

**Comment by makkus** [comment]
Thanks @kemitchell, much appreciated. And also thanks for working on this, can't be easy as I'm sure a lot of people have a lot of, let's say... not overly flexible opinions on the subject :-)
I think LicenseZero is a nice (and necessary) breath of fresh air in the current landscape, even though I don't know yet whether it'll be a good fit for any of my own projects. 

I reckon I could always sell private licenses on my own, if I figure the sort of dual licensing I mentioned is the way to go and it's not possible via licensezero.com. But yeah, it might just complicate an already complicated thing.

**Comment by kemitchell** [comment]
> can't be easy as I'm sure a lot of people have a lot of, let's say... not overly flexible opinions on the subject :-)

License Zero came directly from my experience working with open source companies and developers. Many of my clients have been, or become, good friends. Hard work for people I care about is a pleasure, not a burden!

And frankly, outside of OSI's license-review mailing list, response has been almost all constructive, and very positive.

> I reckon I could always sell private licenses on my own, if I figure the sort of dual licensing I mentioned is the way to go and it's not possible via licensezero.com.

As I meant to point out, I believe licensezero.com's [private license](https://licensezero.com/licenses/private) and [waiver](https://licensezero.com/licenses/waiver), the two documents that give private permission, would work fine for `(Parity OR Prosperity)` projects. In particular, see the Background section of the private license, and the first paragraph of the waiver.

What's more, selling through licensezero.com is very intentionally _nonexclusive_. Have a look at the Not Exclusive section of the [agency terms](https://licensezero.com/terms/agency), the agreement developers enter to have licensezero.com sell on their behalf. You are more than welcome to use licensezero.com and also sell licenses yourself!

> But yeah, it might just complicate an already complicated thing.

Licensing is complex, but it needn't be complicated. I'm _very_ interested in starting from the use cases that matter, rather than legal or community theory, and making the use cases that matter as simple as possible.

I'm going to close this for now, since I have a ton of open issues. But feel free to chime in again, or to open new issues on tangents from here. Thanks again!

**Comment by makkus** [comment]
Thanks!

> What's more, selling through licensezero.com is very intentionally nonexclusive. Have a look at the Not Exclusive section of the agency terms, the agreement developers enter to have licensezero.com sell on their behalf. You are more than welcome to use licensezero.com and also sell licenses yourself!

Yes, I meant to say that if it's not possible to sell a Parity/Prosperity dual-licensed project via licensezero.com because of technical reasons (not sure, haven't looked into that at all) I could always setup something myself. Good move on the non-exclusive selling by the way. It's sensible and fair, it builds trust and really makes me want to use licensezero.com! I'll keep my eyes open for Python package support :-)
